### ISSUE TITLE
Cloudflare Turnstile solver not accepting site key: APIError: Some parameters are missing in this request. (ERROR_BAD_PARAMETERS)

### ISSUE THREAD

**Issue by fineless71** [2captcha/2captcha-javascript#3]
The cloudflare turnstile solver seems to not like the sitekey I gave it. I believe the server is checking if the key starts with `0x4AAAAAAAA`, but the sitekey doesn't, as it starts with `0x4AAAAAAAD`. If I replace the `D` with an `A`, it doesn't immediately give me an error (but this of course isn't the correct sitekey)

![image](https://github.com/2captcha/2captcha-javascript/assets/118756680/fac39f52-0aca-4437-816e-f63a1b1d56e9)

**Comment by dzmitry-duboyski** [comment]
@fineless71 could you provide the url of the page where the captcha is located

**Comment by fineless71** [comment]
Here's an example URL: https://topminecraftservers.org/vote/2515
![image](https://github.com/2captcha/2captcha-javascript/assets/118756680/ab24278f-3261-408e-8763-f2493bc6e5eb)

This page is triggered under any `/vote/` path on their website, even with a residential proxy. Once you solve it you can clear cookies to trigger it again, for testing.

**Comment by dzmitry-duboyski** [comment]
@fineless71 hello.
Cloudflare captcha has two types. The Cloudflare challenge page is located on you page. More details on how to solve this type of captcha are described in the [article](https://2captcha.com/blog/bypassing-cloudflare-challenge-with-puppeteer-and-2captcha).

There is a great [example demonstrating how to bypass Cloudflare challenge page](https://github.com/2captcha/cloudflare-demo). Just [change the `URL`](https://github.com/2captcha/cloudflare-demo/blob/8d02fcdb21272af0caa680187d6732d9014a8cd9/index.js#L42) of the page to the one you need in example, the captcha will be solved successfully.

Please let me know if you have any problems.

**Comment by fineless71** [comment]
Thanks, the article and that example was very helpful. I got it working now, thanks!

**Comment by dzmitry-duboyski** [comment]
@fineless71 You’re welcome
